# Generated by Django 5.1 on 2024-08-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemodels',
            options={'verbose_name_plural': 'Service'},
        ),
    ]
