# Generated by Django 5.1 on 2024-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicemodels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodels',
            name='image',
            field=models.ImageField(upload_to='service/images/'),
        ),
    ]
