# Generated by Django 5.1 on 2024-09-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐ ⭐ ', '⭐ ⭐'), ('⭐ ⭐ ⭐', '⭐ ⭐ ⭐'), ('⭐ ⭐ ⭐ ⭐', '⭐ ⭐ ⭐ ⭐'), ('⭐ ⭐ ⭐ ⭐ ⭐', '⭐ ⭐ ⭐ ⭐ ⭐')], max_length=10),
        ),
    ]
